Repository Lightning-AI/lightning-hpo, pull requests merged in 2022-09, with the labels that each got.

#39 Add show sweeps command
  MANIFEST.in
  lightning_hpo/commands/sweep/run_sweep.py
  lightning_hpo/commands/sweep/show_sweeps.py
  lightning_hpo/controllers/sweeper.py
  tests/commands/__init__.py
  tests/commands/sweep/__init__.py
  tests/commands/sweep/sweep_1.json
  tests/commands/sweep/test_show_sweep.py
  tests/test_examples.py
Labels: enhancement

#63 Delete Sweep
  examples/2_app_pytorch_lightning.py
  examples/scripts/train.py
  lightning_hpo/app/main.py
  lightning_hpo/commands/sweep/delete_sweep.py
  lightning_hpo/components/servers/db/server.py
  lightning_hpo/components/servers/file_server.py
  lightning_hpo/components/sweep.py
  lightning_hpo/controllers/sweeper.py
  tests/commands/sweep/test_delete_sweep.py
Labels: enhancement

#84 UI build / dev guide
  lightning_hpo/app/ui/README.md
Labels: documentation

#85 Add initial table of notebooks
  .gitignore
  lightning_hpo/app/ui/build/asset-manifest.json
  lightning_hpo/app/ui/build/index.html
  lightning_hpo/app/ui/build/static/js/main.017c4de6.js
  lightning_hpo/app/ui/build/static/js/main.017c4de6.js.LICENSE.txt
  lightning_hpo/app/ui/build/static/js/main.017c4de6.js.map
  lightning_hpo/app/ui/build/static/js/main.8c23e466.js
  lightning_hpo/app/ui/build/static/js/main.8c23e466.js.map
  lightning_hpo/app/ui/build/static/media/error.11892047d0183a4723b91dc0fb98cb95.svg
  lightning_hpo/app/ui/build/static/media/success.5edae4c5b171e2c1c5a3c54273c47ba8.svg
  lightning_hpo/app/ui/build/static/media/warning.5c542673e84e77ceb6a230bfea7f7263.svg
  lightning_hpo/app/ui/package.json
  lightning_hpo/app/ui/src/App.tsx
  lightning_hpo/app/ui/src/components/TableContainer.tsx
  lightning_hpo/app/ui/src/components/Tabs.tsx
  lightning_hpo/app/ui/src/generated/models/DownloadArtefactsConfig.ts
  lightning_hpo/app/ui/src/generated/models/ShowArtefactsConfig.ts
  lightning_hpo/app/ui/yarn.lock
Labels: ui

#95 Add tabs and only call API for current tab
  lightning_hpo/app/ui/build/asset-manifest.json
  lightning_hpo/app/ui/build/index.html
  lightning_hpo/app/ui/build/static/js/main.2dda5f91.js
  lightning_hpo/app/ui/build/static/js/main.2dda5f91.js.LICENSE.txt
  lightning_hpo/app/ui/build/static/js/main.2dda5f91.js.map
  lightning_hpo/app/ui/build/static/js/main.d3a6a246.js
  lightning_hpo/app/ui/build/static/js/main.d3a6a246.js.map
  lightning_hpo/app/ui/src/App.tsx
  lightning_hpo/app/ui/src/components/SweepTable.tsx
  lightning_hpo/app/ui/src/components/Tabs.tsx
  lightning_hpo/app/ui/src/hooks/useClientDataState.tsx
  lightning_hpo/app/ui/src/hooks/useSelectedTabState.tsx
Labels: ui

#100 Update table and link styles
  lightning_hpo/app/ui/build/asset-manifest.json
  lightning_hpo/app/ui/build/index.html
  lightning_hpo/app/ui/build/static/js/main.a5801f9f.js
  lightning_hpo/app/ui/build/static/js/main.a5801f9f.js.LICENSE.txt
  lightning_hpo/app/ui/build/static/js/main.a5801f9f.js.map
  lightning_hpo/app/ui/build/static/js/main.e39857f4.js
  lightning_hpo/app/ui/build/static/js/main.e39857f4.js.map
  lightning_hpo/app/ui/src/App.tsx
  lightning_hpo/app/ui/src/components/SweepTable.tsx
  lightning_hpo/app/ui/src/components/TableContainer.tsx
  lightning_hpo/app/ui/src/components/Tabs.tsx
Labels: ui

#110 Add new notebook dialog
  lightning_hpo/app/ui/build/asset-manifest.json
  lightning_hpo/app/ui/build/index.html
  lightning_hpo/app/ui/build/static/js/main.0c349146.js
  lightning_hpo/app/ui/build/static/js/main.0c349146.js.map
  lightning_hpo/app/ui/build/static/js/main.c8129c21.js
  lightning_hpo/app/ui/build/static/js/main.c8129c21.js.LICENSE.txt
  lightning_hpo/app/ui/build/static/js/main.c8129c21.js.map
  lightning_hpo/app/ui/src/components/LightningToggleButtonGroup.tsx
  lightning_hpo/app/ui/src/components/NewMenu.tsx
  lightning_hpo/app/ui/src/components/NewNotebookDialog.tsx
  lightning_hpo/app/ui/src/components/Tabs.tsx
Labels: ui

#111 Add sweep user guide and copy command buttons
  lightning_hpo/app/ui/build/asset-manifest.json
  lightning_hpo/app/ui/build/index.html
  lightning_hpo/app/ui/build/static/js/main.a8fca89e.js
  lightning_hpo/app/ui/build/static/js/main.a8fca89e.js.LICENSE.txt
  lightning_hpo/app/ui/build/static/js/main.a8fca89e.js.map
  lightning_hpo/app/ui/build/static/js/main.c8129c21.js
  lightning_hpo/app/ui/build/static/js/main.c8129c21.js.map
  lightning_hpo/app/ui/src/App.tsx
  lightning_hpo/app/ui/src/components/SweepTable.tsx
  lightning_hpo/app/ui/src/components/UserGuide.tsx
Labels: ui

#114 Add help button linking to docs
  lightning_hpo/app/ui/build/asset-manifest.json
  lightning_hpo/app/ui/build/index.html
  lightning_hpo/app/ui/build/static/js/main.65a4bb75.js
  lightning_hpo/app/ui/build/static/js/main.65a4bb75.js.LICENSE.txt
  lightning_hpo/app/ui/build/static/js/main.65a4bb75.js.map
  lightning_hpo/app/ui/build/static/js/main.a8fca89e.js
  lightning_hpo/app/ui/build/static/js/main.a8fca89e.js.map
  lightning_hpo/app/ui/src/components/Tabs.tsx
Labels: ui

#148 Fix bugs in requirements from the CLI
  lightning_hpo/commands/notebook/run.py
  lightning_hpo/commands/sweep/run.py
Labels: bug

#149 Fix issue with special characters and `desired_state`
  lightning_hpo/commands/notebook/run.py
  lightning_hpo/components/notebook.py
  lightning_hpo/controllers/notebook.py
  lightning_hpo/controllers/sweep.py
  lightning_hpo/controllers/tensorboard.py
Labels: bug

#160 Add sweep story tests
  lightning_hpo/commands/notebook/show.py
  lightning_hpo/commands/sweep/run.py
  lightning_hpo/loggers/tensorboard.py
  requirements.txt
  tests/features/notebook.feature
  tests/features/steps/notebook.py
  tests/features/steps/sweep.py
  tests/features/sweep.feature
Labels: testing
